name: Docs Preview

on:
  pull_request:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install uv
          uv pip install -e .
          uv pip install sphinx sphinx_rtd_theme sphinxcontrib-mermaid sphinx_sitemap
      - name: Build docs
        run: |
          cd docs
          make html
      - name: Deploy preview to gh-pages-preview
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          publish_branch: gh-pages-preview
          force_orphan: true
